[package]
name = "utils"
version = "0.0.11"
edition = "2021"
publish = false

[dependencies]
texture-common = { workspace = true }
super-lendy = { path = "../program" }
solana-sdk = "1.16.18"
solana-client = "1.16.18"
solana-account-decoder = "1.16.18"
anyhow = "1.0.52"
